CREATE TABLE `company_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`companyName` varchar(256) NOT NULL,
	`siret` varchar(14),
	`vatNumber` varchar(32),
	`address` text,
	`phone` varchar(20),
	`email` varchar(256),
	`website` varchar(256),
	`logoUrl` text,
	`logoKey` varchar(512),
	`legalMentions` text,
	`paymentTerms` varchar(256) DEFAULT '30 jours net',
	`paymentConditions` text,
	`bankDetails` text,
	`signature` text,
	`signatureUrl` text,
	`signatureKey` varchar(512),
	`defaultVatRate` int DEFAULT 20,
	`invoicePrefix` varchar(10) DEFAULT 'FA',
	`quotePrefix` varchar(10) DEFAULT 'DV',
	`creditPrefix` varchar(10) DEFAULT 'AV',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `company_settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `company_settings_userId_unique` UNIQUE(`userId`)
);
